name: photonator
channels:
  - conda-forge
  - nvidia

dependencies:
  - python>=3.14
  - numpy>=1.24
  - scipy>=1.10
  - h5py>=3.8
  - pytest>=7.0
  - matplotlib
  - seaborn
  - ruff
  - mypy
  - pip
  - numba>=0.57
  - cupy
